version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/CodePipeline_Assignment
    overwrite: true
hooks:
  BeforeInstall:
    - location: install_depedencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    # - location: scripts/install_python3_dependencies.sh
    #   timeout: 300
    #   runas: root
    - location: start_server.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 30
      runas: root