version: 0.0
os: linux
files:
  - source: /
    destination: /
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/install_depedencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_python3_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/start_server.sh
      timeout: 30
      runas: ubuntu
    - location: scripts/start_server.sh
      timeout: 30
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ubuntu